/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiApplicationsRouteImport } from './routes/api/applications'
import { Route as ApiInquiriesRouteImport } from './routes/api/inquiries'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as CareersSlugRouteImport } from './routes/careers/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ApiAdminMediaRouteImport } from './routes/api/admin/media'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminPrivateUrlRouteImport } from './routes/api/admin/private-url'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiContentCollectionRouteImport } from './routes/api/content/$collection'
import { Route as ApiCronRetentionRouteImport } from './routes/api/cron/retention'
import { Route as ApiCronRetryWhatsappRouteImport } from './routes/api/cron/retry-whatsapp'
import { Route as ApiUploadsSignRouteImport } from './routes/api/uploads/sign'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as ApiAdminContentCollectionRouteImport } from './routes/api/admin/content/$collection'
import { Route as ApiAdminInboxCollectionRouteImport } from './routes/api/admin/inbox/$collection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplicationsRoute = ApiApplicationsRouteImport.update({
  id: '/api/applications',
  path: '/api/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiriesRoute = ApiInquiriesRouteImport.update({
  id: '/api/inquiries',
  path: '/api/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPrivateUrlRoute = ApiAdminPrivateUrlRouteImport.update({
  id: '/api/admin/private-url',
  path: '/api/admin/private-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentCollectionRoute = ApiContentCollectionRouteImport.update({
  id: '/api/content/$collection',
  path: '/api/content/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRetentionRoute = ApiCronRetentionRouteImport.update({
  id: '/api/cron/retention',
  path: '/api/cron/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRetryWhatsappRoute = ApiCronRetryWhatsappRouteImport.update({
  id: '/api/cron/retry-whatsapp',
  path: '/api/cron/retry-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsSignRoute = ApiUploadsSignRouteImport.update({
  id: '/api/uploads/sign',
  path: '/api/uploads/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentCollectionRoute =
  ApiAdminContentCollectionRouteImport.update({
    id: '/api/admin/content/$collection',
    path: '/api/admin/content/$collection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminInboxCollectionRoute = ApiAdminInboxCollectionRouteImport.update({
  id: '/api/admin/inbox/$collection',
  path: '/api/admin/inbox/$collection',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/private-url': typeof ApiAdminPrivateUrlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/$collection': typeof ApiContentCollectionRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/cron/retry-whatsapp': typeof ApiCronRetryWhatsappRoute
  '/api/uploads/sign': typeof ApiUploadsSignRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/admin/content/$collection': typeof ApiAdminContentCollectionRoute
  '/api/admin/inbox/$collection': typeof ApiAdminInboxCollectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/careers': typeof CareersIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/private-url': typeof ApiAdminPrivateUrlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/$collection': typeof ApiContentCollectionRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/cron/retry-whatsapp': typeof ApiCronRetryWhatsappRoute
  '/api/uploads/sign': typeof ApiUploadsSignRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/admin/content/$collection': typeof ApiAdminContentCollectionRoute
  '/api/admin/inbox/$collection': typeof ApiAdminInboxCollectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/service-areas': typeof ServiceAreasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/applications': typeof ApiApplicationsRoute
  '/api/inquiries': typeof ApiInquiriesRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/private-url': typeof ApiAdminPrivateUrlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/content/$collection': typeof ApiContentCollectionRoute
  '/api/cron/retention': typeof ApiCronRetentionRoute
  '/api/cron/retry-whatsapp': typeof ApiCronRetryWhatsappRoute
  '/api/uploads/sign': typeof ApiUploadsSignRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/api/admin/content/$collection': typeof ApiAdminContentCollectionRoute
  '/api/admin/inbox/$collection': typeof ApiAdminInboxCollectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/robots.txt'
    | '/service-areas'
    | '/sitemap.xml'
    | '/api/applications'
    | '/api/inquiries'
    | '/careers/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/careers/'
    | '/projects/'
    | '/services/'
    | '/api/admin/media'
    | '/api/admin/overview'
    | '/api/admin/private-url'
    | '/api/auth/$'
    | '/api/content/$collection'
    | '/api/cron/retention'
    | '/api/cron/retry-whatsapp'
    | '/api/uploads/sign'
    | '/api/webhooks/whatsapp'
    | '/api/admin/content/$collection'
    | '/api/admin/inbox/$collection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/robots.txt'
    | '/service-areas'
    | '/sitemap.xml'
    | '/api/applications'
    | '/api/inquiries'
    | '/careers/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/admin'
    | '/careers'
    | '/projects'
    | '/services'
    | '/api/admin/media'
    | '/api/admin/overview'
    | '/api/admin/private-url'
    | '/api/auth/$'
    | '/api/content/$collection'
    | '/api/cron/retention'
    | '/api/cron/retry-whatsapp'
    | '/api/uploads/sign'
    | '/api/webhooks/whatsapp'
    | '/api/admin/content/$collection'
    | '/api/admin/inbox/$collection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/robots.txt'
    | '/service-areas'
    | '/sitemap.xml'
    | '/api/applications'
    | '/api/inquiries'
    | '/careers/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/careers/'
    | '/projects/'
    | '/services/'
    | '/api/admin/media'
    | '/api/admin/overview'
    | '/api/admin/private-url'
    | '/api/auth/$'
    | '/api/content/$collection'
    | '/api/cron/retention'
    | '/api/cron/retry-whatsapp'
    | '/api/uploads/sign'
    | '/api/webhooks/whatsapp'
    | '/api/admin/content/$collection'
    | '/api/admin/inbox/$collection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiApplicationsRoute: typeof ApiApplicationsRoute
  ApiInquiriesRoute: typeof ApiInquiriesRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRoute
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminPrivateUrlRoute: typeof ApiAdminPrivateUrlRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiContentCollectionRoute: typeof ApiContentCollectionRoute
  ApiCronRetentionRoute: typeof ApiCronRetentionRoute
  ApiCronRetryWhatsappRoute: typeof ApiCronRetryWhatsappRoute
  ApiUploadsSignRoute: typeof ApiUploadsSignRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
  ApiAdminContentCollectionRoute: typeof ApiAdminContentCollectionRoute
  ApiAdminInboxCollectionRoute: typeof ApiAdminInboxCollectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/applications': {
      id: '/api/applications'
      path: '/api/applications'
      fullPath: '/api/applications'
      preLoaderRoute: typeof ApiApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiries': {
      id: '/api/inquiries'
      path: '/api/inquiries'
      fullPath: '/api/inquiries'
      preLoaderRoute: typeof ApiInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/private-url': {
      id: '/api/admin/private-url'
      path: '/api/admin/private-url'
      fullPath: '/api/admin/private-url'
      preLoaderRoute: typeof ApiAdminPrivateUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/$collection': {
      id: '/api/content/$collection'
      path: '/api/content/$collection'
      fullPath: '/api/content/$collection'
      preLoaderRoute: typeof ApiContentCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retention': {
      id: '/api/cron/retention'
      path: '/api/cron/retention'
      fullPath: '/api/cron/retention'
      preLoaderRoute: typeof ApiCronRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/retry-whatsapp': {
      id: '/api/cron/retry-whatsapp'
      path: '/api/cron/retry-whatsapp'
      fullPath: '/api/cron/retry-whatsapp'
      preLoaderRoute: typeof ApiCronRetryWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/sign': {
      id: '/api/uploads/sign'
      path: '/api/uploads/sign'
      fullPath: '/api/uploads/sign'
      preLoaderRoute: typeof ApiUploadsSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content/$collection': {
      id: '/api/admin/content/$collection'
      path: '/api/admin/content/$collection'
      fullPath: '/api/admin/content/$collection'
      preLoaderRoute: typeof ApiAdminContentCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inbox/$collection': {
      id: '/api/admin/inbox/$collection'
      path: '/api/admin/inbox/$collection'
      fullPath: '/api/admin/inbox/$collection'
      preLoaderRoute: typeof ApiAdminInboxCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiApplicationsRoute: ApiApplicationsRoute,
  ApiInquiriesRoute: ApiInquiriesRoute,
  CareersSlugRoute: CareersSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiAdminMediaRoute: ApiAdminMediaRoute,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminPrivateUrlRoute: ApiAdminPrivateUrlRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiContentCollectionRoute: ApiContentCollectionRoute,
  ApiCronRetentionRoute: ApiCronRetentionRoute,
  ApiCronRetryWhatsappRoute: ApiCronRetryWhatsappRoute,
  ApiUploadsSignRoute: ApiUploadsSignRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
  ApiAdminContentCollectionRoute: ApiAdminContentCollectionRoute,
  ApiAdminInboxCollectionRoute: ApiAdminInboxCollectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
